### ISSUE TITLE
Download url broke again in viddy 1.x

### ISSUE THREAD

**Issue by kr3cj** [ryodocx/asdf-viddy#9]
Thanks for making this tool! I use it a lot and noticed a recent problem.

When trying to install any `viddy` releases at or above version `1.0`, `asdf` throws a `404` for the download URL. Looks like the `viddy` repo changed from using `Darwin` to `macos` in the [release download naming convention](https://github.com/sachaos/viddy/releases/tag/v1.1.2).

```sh
$ asdf install viddy 1.0.0
* Downloading viddy release 1.0.0...
curl: (22) The requested URL returned error: 404
asdf-viddy: Could not download https://github.com/sachaos/viddy/releases/download/v1.0.0/viddy_Darwin_x86_64.tar.gz
```

Correct download url should be 
`https://github.com/sachaos/viddy/releases/download/v1.0.0/viddy-v1.0.0-macos-x86_64.tar.gz`

**Comment by ryodocx** [comment]
resolved by #8
